packages:
  - rsx-vscode
  - rsx-language-server

onlyBuiltDependencies:
  - esbuild
  - tree-sitter
  - tree-sitter-css
  - tree-sitter-html
  - tree-sitter-rust
  - tree-sitter-scss
  - tree-sitter-typescript
